# Generated by Django 2.2.19 on 2022-11-07 18:54

import django.db.models.deletion as delete
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=delete.CASCADE,
                                    to='posts.Group'),
        ),
    ]
