# Generated by Django 2.2.16 on 2022-12-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20221218_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='edit_time',
        ),
    ]
