# Generated by Django 2.2.16 on 2022-12-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_edit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='was_edited',
            field=models.BooleanField(default=False),
        ),
    ]
