# Generated by Django 2.2.16 on 2022-12-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_post_was_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.CharField(blank=True, max_length=25, verbose_name='Здесь может быть заголовок'),
        ),
    ]
