# Generated by Django 2.2.16 on 2022-12-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='was_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок'),
        ),
    ]
