# Generated by Django 2.2.16 on 2022-12-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20221224_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
