# Generated by Django 2.2.16 on 2022-12-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_post_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='was_edited',
        ),
    ]
